apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: hypersnap-grafana-config
    files:
      - grafana/grafana.ini
  - name: hypersnap-grafana-datasource
    files:
      - grafana/datasource.yaml
  - name: hypersnap-grafana-dashboard-provider
    files:
      - grafana/dashboards.yaml
  - name: hypersnap-grafana-dashboard
    files:
      - grafana/dashboard.json
resources:
  - configmap.yaml
  - grafana-pvc.yaml
  - grafana-service.yaml
  - grafana-deployment.yaml
  - grafana-ingress.yaml
  - pvc.yaml
  - service.yaml
  - statsd-deployment.yaml
  - statefulset.yaml
  - ingress.yaml
  - ingressroute-tcp.yaml
  - ingressroute-udp.yaml
