apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - statsd-deployment.yaml
  - statefulset.yaml
  - ingress.yaml
  - ingressroute-tcp.yaml
  - ingressroute-udp.yaml
