apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-traefik.yaml
  - platform-dns.yaml
  - platform-authentik.yaml
  - platform-argo-ingress.yaml
  - apps-chat.yaml
  - apps-cloud.yaml
  - apps-meshcentral.yaml
  - apps-pad.yaml
