ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    ingressClass: traefik
  kubernetesIngress:
    ingressClass: traefik

deployment:
  revisionHistoryLimit: 2

ports:
  traefik:
    expose:
      default: false
  web: null
  websecure:
    asDefault: true
    expose:
      default: true
  dns-tcp:
    port: 1053
    exposedPort: 53
    protocol: TCP
    expose:
      default: true
  dns-udp:
    port: 1054
    exposedPort: 53
    protocol: UDP
    expose:
      default: true
  hypersnap-gossip:
    port: 3382
    exposedPort: 3382
    protocol: UDP
    expose:
      default: true
  hypersnap-grpc:
    port: 3383
    exposedPort: 3383
    protocol: TCP
    expose:
      default: true

service:
  type: LoadBalancer
  single: false

tolerations:
  - key: node.kubernetes.io/disk-pressure
    operator: Exists
    effect: NoSchedule

priorityClassName: system-cluster-critical

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 512Mi

certificatesResolvers:
  le:
    acme:
      email: admin@x43.io
      storage: /data/acme.json
      tlsChallenge: true

persistence:
  enabled: true
  path: /data
