apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:33.0.2-apache
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: mariadb-password
            - name: MYSQL_HOST
              value: cloud-db
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: nextcloud-admin-user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: nextcloud-admin-password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: drive.x43.io
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
            - name: OVERWRITEHOST
              value: drive.x43.io
            - name: OVERWRITEPROTOCOL
              value: https
            - name: OVERWRITECLIURL
              value: https://drive.x43.io
            - name: NEXTCLOUD_INIT_HTACCESS
              value: "true"
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/www/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cloud-data
