#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib/in-cluster-secrets.sh
source "$SCRIPT_DIR/lib/in-cluster-secrets.sh"

usage() {
  cat <<'USAGE'
Usage: ensure-app-secrets.sh [--all|--cloud|--chat|--pad] [--restart]

Generate missing disposable app bootstrap secrets as Kubernetes Secrets.
Secret values are generated by a short-lived Kubernetes Job inside the target
namespace, sent only to the Kubernetes API, and never printed or written to git.

Options:
  --all       Ensure cloud, chat, and pad secrets (default)
  --cloud     Ensure Nextcloud secrets only
  --chat      Ensure Mattermost secrets only
  --pad       Ensure CryptPad secrets only
  --restart   Roll deployments after creating any missing secrets
USAGE
}

ensure_kubectl() {
  if command -v kubectl >/dev/null 2>&1; then
    return
  fi

  echo "kubectl is required to create Kubernetes Secrets." >&2
  exit 1
}

secret_exists() {
  local namespace=$1
  local name=$2
  kubectl -n "$namespace" get secret "$name" >/dev/null 2>&1
}

created_any=0
restart=0
ensure_cloud=0
ensure_chat=0
ensure_pad=0

if [[ $# -eq 0 ]]; then
  ensure_cloud=1
  ensure_chat=1
  ensure_pad=1
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)
      ensure_cloud=1
      ensure_chat=1
      ensure_pad=1
      ;;
    --cloud)
      ensure_cloud=1
      ;;
    --chat)
      ensure_chat=1
      ;;
    --pad)
      ensure_pad=1
      ;;
    --restart)
      restart=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
  shift
done

ensure_kubectl

if [[ "$ensure_cloud" -eq 1 ]]; then
  if secret_exists cloud cloud-secrets; then
    echo "cloud/cloud-secrets already exists; leaving it unchanged."
  else
    ensure_generated_secret cloud cloud-secrets \
      --hex mariadb-root-password 32 \
      --hex mariadb-password 32 \
      --literal "nextcloud-admin-user=${NEXTCLOUD_ADMIN_USER:-cloudadmin}" \
      --hex nextcloud-admin-password 32
    if [[ "$GENERATED_SECRET_CREATED" -eq 1 ]]; then
      created_any=1
    fi
  fi

  if [[ "$restart" -eq 1 ]]; then
    kubectl -n cloud rollout restart deployment/cloud-db deployment/cloud >/dev/null 2>&1 || true
  fi
fi

if [[ "$ensure_chat" -eq 1 ]]; then
  if secret_exists chat chat-secrets; then
    echo "chat/chat-secrets already exists; leaving it unchanged."
  else
    ensure_generated_secret chat chat-secrets \
      --hex postgres-password 32
    if [[ "$GENERATED_SECRET_CREATED" -eq 1 ]]; then
      created_any=1
    fi
  fi

  if [[ "$restart" -eq 1 ]]; then
    kubectl -n chat rollout restart deployment/chat-db deployment/chat >/dev/null 2>&1 || true
  fi
fi

if [[ "$ensure_pad" -eq 1 ]]; then
  if secret_exists pad pad-secrets; then
    echo "pad/pad-secrets already exists; leaving it unchanged."
  else
    ensure_generated_secret pad pad-secrets \
      --hex login_salt 32
    if [[ "$GENERATED_SECRET_CREATED" -eq 1 ]]; then
      created_any=1
    fi
  fi

  if [[ "$restart" -eq 1 ]]; then
    kubectl -n pad rollout restart deployment/pad >/dev/null 2>&1 || true
  fi
fi

if [[ "$created_any" -eq 0 ]]; then
  echo "No missing app secrets found."
fi
