apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components (ingress/auth/argo)
  sourceRepos:
    - https://github.com/your-org/danto-gitops
    - https://helm.traefik.io/traefik
    - https://charts.goauthentik.io
  destinations:
    - namespace: traefik
      server: https://kubernetes.default.svc
    - namespace: authentik
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
